# Generated by Django 3.1.7 on 2021-03-05 03:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_app', '0003_category_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ExpenseCategory',
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'Expense Categories'},
        ),
    ]
