# Generated by Django 3.1.7 on 2021-03-05 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0004_auto_20210305_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
